# Generated by Django 3.2.21 on 2023-12-09 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pefa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('founding_year', models.CharField(max_length=10)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('description_3', models.TextField()),
                ('background_image_1', models.ImageField(blank=True, upload_to='church_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('background_image_2', models.ImageField(blank=True, upload_to='church_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('background_image_3', models.ImageField(blank=True, upload_to='church_backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('mission', models.TextField(help_text='Enter the mission statement of the organization')),
                ('vision', models.TextField(help_text='Enter the vision statement of the organization')),
                ('slogan', models.CharField(help_text="Enter the organization's slogan (e.g., a short tagline)", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the ministry name', max_length=100)),
                ('background_image', models.ImageField(blank=True, upload_to='ministries/')),
                ('background_text', models.TextField(help_text='Enter a detailed ministry description')),
                ('description', models.TextField(help_text='Enter a detailed ministry description')),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='ministries', to='pefa.church')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(help_text='Select or upload a video file', upload_to='church_gallery_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])])),
                ('title', models.CharField(help_text='Enter the video title', max_length=100)),
                ('description', models.TextField(help_text='Enter a detailed video description')),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='pefa.church')),
                ('ministries', models.ManyToManyField(blank=True, related_name='ministry_vids', to='pefa.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the sermon', max_length=100)),
                ('preacher', models.CharField(help_text="Enter the preacher's name", max_length=100)),
                ('date', models.DateField(help_text='Select the date of the sermon')),
                ('scripture_references', models.TextField(help_text='Enter scripture references (e.g., John 3:16-18)')),
                ('description', models.TextField(blank=True, help_text='Enter a detailed description of the sermon (optional)')),
                ('audio_file', models.FileField(blank=True, help_text='Upload an audio file of the sermon (optional)', upload_to='sermon_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])])),
                ('image', models.ImageField(blank=True, help_text='Upload an image related to the sermon (optional)', upload_to='sermon_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('video', models.FileField(blank=True, help_text='Upload a video related to the sermon (optional)', upload_to='sermon_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])])),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='pefa.church')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the prayer request', max_length=100)),
                ('description', models.TextField(help_text='Enter a detailed description of the request')),
                ('requester_name', models.CharField(help_text='Enter your name', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date the request was created')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='pefa.church')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Select or upload an image file', upload_to='church_gallery_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('description', models.TextField(help_text='Enter a detailed image description')),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pefa.church')),
                ('ministries', models.ManyToManyField(blank=True, related_name='ministry_imgs', to='pefa.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the event name', max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='events/')),
                ('date', models.DateField(help_text='Select the event date')),
                ('description', models.TextField(help_text='Enter a detailed event description')),
                ('location', models.CharField(help_text='Enter the event location', max_length=100)),
                ('church', models.ForeignKey(help_text='Select the associated church', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pefa.church')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchOfficial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the official', max_length=100)),
                ('position', models.CharField(help_text='Select the position of the official', max_length=50)),
                ('email', models.EmailField(blank=True, help_text="Enter the official's email (optional)", max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, help_text="Enter the official's address (optional)")),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the official (optional)', upload_to='official_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pefa.church')),
            ],
        ),
    ]
